<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <base href="/localhost">
    <title><?= $title ?></title>
    <meta name="description" content="<?= $description ?>" />
    <meta name="keywords" content="<?= $keywords ?>" />
    <link rel="stylesheet" href="assets/css/style.css">

</head>
<body>

<nav class="navbar">
    <span class="logo">Logo</span>
    <ul>
        <li><a href="register">Registrace</a></li>
        <li><a href="login">Přihlášení</a></li>
        <li><a href="homepage">Homepage</a></li>
        <li><a href="logout">Odhlásit se</a></li>
    </ul>
</nav>

<?php foreach ($messages as $message) : ?>
            <div class="alert <?=$message["typ"]?>">
               <h4><?= $message["title"]?></h4>
               <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
               <p><?= $message["content"]?></p>
            </div>
<?php endforeach ?>	

    <h2> <?php if ($this->controller->currentUser("username") == null) echo(""); else echo($this->controller->currentUser("username")); ?> </h2>
    <?php $this->controller->returnView(); ?>	


</body>
</html>